### ISSUE TITLE
Install4J apps support

### ISSUE THREAD

**Issue by Witchilich** [appget/appget.packages#4523]
Is Install4J supported ? I specifically mean this
https://github.com/BiglySoftware/BiglyBT
```
id: biglybt
name: BiglyBT
version: 2.1.0.0
home: https://www.biglybt.com/
installMethod: ???
args: -q
installers:
- location: https://files.biglybt.com/installer/BiglyBT_Installer64.exe
  sha256: efc74ad83cd208d08463b5affbd3c9e1d5216cae7345e14689c461b90ae49d50
- location: https://files.biglybt.com/installer/BiglyBT_Installer32.exe
  sha256: 611ba0372f75b54a94b1da3e171dfbbef4a9a9085ebf0e760711d6e36170f4f7
  architecture: x64 
```
